---
name: Build Container
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: demo
  REGION: asia-southeast1

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authorize Docker Push
        run: |-
          gcloud auth configure-docker

      - name: Build Container
        run: |-
          docker build -t asia.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }} -f build/Dockerfile .
    