---
name: Build and Deploy container to GCP Cloud Run
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: demo
  REGION: asia-southeast1

on:
  create:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build and Deploy Container to GCP Cloud Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Environment
        run: |-
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authorize Docker Push
        run: |-
          gcloud auth configure-docker

      - name: Build Container
        run: |-
          docker build -t asia.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ env.RELEASE_VERSION }} -f build/Dockerfile .
      
      - name: Push Container
        run: |-
          docker push asia.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ env.RELEASE_VERSION }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          image: asia.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ env.RELEASE_VERSION }}
          region: ${{ env.REGION }}
          flags: --service-account=${{ secrets.GCP_SA_EMAIL }} --concurrency=10 --cpu=1 --max-instances=5 --memory=512Mi --min-instances=1 --port=80 --allow-unauthenticated
          env_vars: RELEASE_VERSION=${{ env.RELEASE_VERSION }}

      - name: Show Output
        run: |-
          echo ${{ steps.deploy.outputs.url }}
    